// Package codec is the dataset serializer/deserializer: schema-directed
// decoding of instance documents into Go values (generated by codegen, or
// reflective) and canonical encoding back out. It is built for MINIMAL
// ALLOCATION on the hot path.
//
// Two decode paths, one semantics (docs/ARCHITECTURE.md):
//
//   - Runtime path: facet pipeline + value.Mapping, schema-driven,
//     always available. Hot-path APIs follow the appender convention
//     (AppendCanonical(dst []byte, v) []byte, ParseBytes([]byte)) so
//     even this path stays allocation-frugal.
//   - Generated fast path: code emitted at codegen time by the value
//     backend's emitter (see codegen doc) parses directly from the
//     reader's byte window into target fields — no intermediate string,
//     no boxed value.Value, facet checks inlined.
//
// DIFFERENTIAL TESTING is the correctness contract between them: both
// paths implement the same pipeline stages with the same spec rule IDs,
// and property tests feed identical inputs to both, requiring identical
// values and identical error rule IDs. A fast path that disagrees with
// the runtime path is wrong by definition. Allocation budgets are
// enforced by benchmarks (testing.AllocsPerRun): scalar decode on the
// fast path targets zero allocations.
//
// Debuggability (extending STYLE E1–E3): every decode error localizes the
// failure without a debugger — it names the pipeline stage that rejected
// (whitespace / pattern / lexical-map / facet / assertion), the type
// QName, the offending input fragment, and the instance Loc + byte
// offset. GOXSD_DEBUG=codec traces stage transitions per value through
// the injected slog logger, so one value's path through the pipeline can
// be watched end to end.
//
// Further contract:
//
//   - Decode validates as it reads — a decoded value is a valid value.
//   - Encode emits canonical lexical forms deterministically: attribute
//     and element order fixed by the schema and document order, never map
//     order (STYLE D1/D2).
//   - Round-trip property: decode∘encode = identity on canonical
//     instances; enforced across the W3C suite instances (M8 acceptance).
//   - Backend-agnostic via value.Backend — strict, native, or
//     user-supplied per value.Override, each with or without an emitter.
//
// Grown during milestone M8 (docs/PLAN.md).
package codec
